name: Multi-OS Testing
on: [push]
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on Linux"
  test-windows:
    runs-on: windows-latest
    steps:
      - run: echo "Running on Windows"
  test-macos:
    runs-on: macos-latest
    steps:
      - run: echo "Running on macOS"
