name: Secrets & Env Vars
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    env:
      API_URL: https://api.example.com
    steps:
      - run: echo "Using secret key: ${{ secrets.MY_API_KEY }}"
