#Nodejs test workflow
name: Node.js CI with Cache

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

